### ISSUE TITLE
你好，请问能否加上拖拽排序呢？

### ISSUE THREAD

**Issue by lvgao2012** [bowencool/super-form#4]
你好，请问能否加上拖拽排序呢？

**Comment by bowencool** [comment]
可以拖动啊，你的不能拖吗？

**Comment by lvgao2012** [comment]
想起来了  是draggable.js的问题，chrome 高版本的不行

**Comment by lvgao2012** [comment]
我现在是chrome 65

**Comment by lvgao2012** [comment]
解决不了啊 唉  sortable.js的问题

**Comment by bowencool** [comment]
我也chrome 65啊，没问题啊。。

**Comment by lvgao2012** [comment]
我的是win7  64位系统  重装chrome还不行

**Comment by bowencool** [comment]
我复现不了，我帮你open吧，看看其他人有没有碰到的

**Comment by lvgao2012** [comment]
vue.draggable  、sortable.js那有很多人有问题  但是没有解决的

**Comment by lvgao2012** [comment]
我把浏览器重置后好了，然后开启扩展程序，发现了有一个划词翻译的插件会影响。所以不能用了，，，但是jquery.sortable.js测试的时候OK的   哈哈哈
